# Generated by Django 2.2.6 on 2019-10-13 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FediverseUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Host', models.URLField()),
                ('Inbox', models.URLField(blank=True, null=True)),
                ('Outbox', models.URLField(blank=True, null=True)),
                ('SharedInbox', models.URLField(blank=True, null=True)),
                ('Featured', models.URLField(blank=True, null=True)),
                ('Followers', models.URLField(blank=True, null=True)),
                ('Following', models.URLField(blank=True, null=True)),
                ('Uri', models.URLField(blank=True, null=True)),
                ('Url', models.URLField(blank=True, null=True)),
                ('publicKey', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_silence', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publicKey', models.TextField(blank=True, editable=False)),
                ('privateKey', models.TextField(blank=True, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
