# Generated by Django 2.2.6 on 2019-11-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0002_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetDomain', models.CharField(max_length=256)),
            ],
        ),
    ]
