# Generated by Django 2.2.6 on 2019-11-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0003_blackdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackdomain',
            name='targetDomain',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
