# Generated by Django 2.2.6 on 2019-11-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0005_fediverseuser_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='fediverse.Post'),
            preserve_default=False,
        ),
    ]
