# Generated by Django 2.2.6 on 2019-10-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0006_auto_20191016_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='announceTo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='replyTo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
