# Generated by Django 2.2.6 on 2019-11-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0006_like_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='fediverse.Post'),
        ),
    ]
