# Generated by Django 2.2.6 on 2019-11-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0007_auto_20191105_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='fediverseuser',
            name='is_manualFollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manualFollow',
            field=models.BooleanField(default=False),
        ),
    ]
