# Generated by Django 2.2.6 on 2019-10-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0009_auto_20191022_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='fediverseuser',
            name='keyId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
