# Generated by Django 2.2.6 on 2019-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0010_fediverseuser_keyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fediverseuser',
            name='keyId',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
