# Generated by Django 2.2.6 on 2019-10-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0011_auto_20191022_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fediID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='announceTo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='replyTo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
