# Generated by Django 2.2.6 on 2019-11-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0012_like_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TombUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('tomb_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
