# Generated by Django 2.2.6 on 2019-10-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0012_auto_20191023_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fediverseuser',
            old_name='name',
            new_name='display_name',
        ),
    ]
