# Generated by Django 2.2.6 on 2019-10-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0013_auto_20191023_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='fediverseuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
