# Generated by Django 2.2.6 on 2019-11-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0014_auto_20191120_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='pendingObj',
            field=models.TextField(blank=True, null=True),
        ),
    ]
