# Generated by Django 2.2.6 on 2019-11-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0014_fediverseuser_is_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='announceTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announced', to='fediverse.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='replyTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='fediverse.Post'),
        ),
    ]
